# Generated by Django 2.2 on 2019-07-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_coupon_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='amount',
        ),
    ]
