# Generated by Django 2.2 on 2019-07-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190719_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='redeem',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
