# Generated by Django 2.2 on 2019-07-19 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190719_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='redeem',
            new_name='amount',
        ),
    ]
